package de.dasbabypixel.gamelauncher.api.util.logging

actual interface Logger {
    actual fun debug(msg: String)
    actual fun debug(format: String, arg: Any)
    actual fun debug(format: String, arg1: Any, arg2: Any)
    actual fun debug(format: String, vararg arguments: Any)
    actual fun debug(msg: String, t: Throwable)
    actual fun debug(marker: Marker, msg: String)
    actual fun debug(marker: Marker, format: String, arg: Any)
    actual fun debug(marker: Marker, format: String, arg1: Any, arg2: Any)
    actual fun debug(marker: Marker, format: String, vararg arguments: Any)
    actual fun debug(marker: Marker, msg: String, t: Throwable)
    actual fun info(msg: String)
    actual fun info(format: String, arg: Any)
    actual fun info(format: String, arg1: Any, arg2: Any)
    actual fun info(format: String, vararg arguments: Any)
    actual fun info(msg: String, t: Throwable)
    actual fun info(marker: Marker, msg: String)
    actual fun info(marker: Marker, format: String, arg: Any)
    actual fun info(marker: Marker, format: String, arg1: Any, arg2: Any)
    actual fun info(marker: Marker, format: String, vararg arguments: Any)
    actual fun info(marker: Marker, msg: String, t: Throwable)
    actual fun warn(msg: String)
    actual fun warn(format: String, arg: Any)
    actual fun warn(format: String, arg1: Any, arg2: Any)
    actual fun warn(format: String, vararg arguments: Any)
    actual fun warn(msg: String, t: Throwable)
    actual fun warn(marker: Marker, msg: String)
    actual fun warn(marker: Marker, format: String, arg: Any)
    actual fun warn(marker: Marker, format: String, arg1: Any, arg2: Any)
    actual fun warn(marker: Marker, format: String, vararg arguments: Any)
    actual fun warn(marker: Marker, msg: String, t: Throwable)
    actual fun error(msg: String)
    actual fun error(format: String, arg: Any)
    actual fun error(format: String, arg1: Any, arg2: Any)
    actual fun error(format: String, vararg arguments: Any)
    actual fun error(msg: String, t: Throwable)
    actual fun error(marker: Marker, msg: String)
    actual fun error(marker: Marker, format: String, arg: Any)
    actual fun error(marker: Marker, format: String, arg1: Any, arg2: Any)
    actual fun error(marker: Marker, format: String, vararg arguments: Any)
    actual fun error(marker: Marker, msg: String, t: Throwable)
}
