package de.dasbabypixel.gamelauncher.api.util.logging

expect interface Logger {
    fun debug(msg: String)
    fun debug(format: String, arg: Any?)
    fun debug(format: String, arg1: Any?, arg2: Any?)
    fun debug(format: String, vararg arguments: Any?)
    fun debug(msg: String, t: Throwable)
    fun debug(marker: Marker, msg: String)
    fun debug(marker: Marker, format: String, arg: Any?)
    fun debug(marker: Marker, format: String, arg1: Any?, arg2: Any?)
    fun debug(marker: Marker, format: String, vararg arguments: Any?)
    fun debug(marker: Marker, msg: String, t: Throwable)

    fun info(msg: String)
    fun info(format: String, arg: Any?)
    fun info(format: String, arg1: Any?, arg2: Any?)
    fun info(format: String, vararg arguments: Any?)
    fun info(msg: String, t: Throwable)
    fun info(marker: Marker, msg: String)
    fun info(marker: Marker, format: String, arg: Any?)
    fun info(marker: Marker, format: String, arg1: Any?, arg2: Any?)
    fun info(marker: Marker, format: String, vararg arguments: Any?)
    fun info(marker: Marker, msg: String, t: Throwable)

    fun warn(msg: String)
    fun warn(format: String, arg: Any?)
    fun warn(format: String, arg1: Any?, arg2: Any?)
    fun warn(format: String, vararg arguments: Any?)
    fun warn(msg: String, t: Throwable)
    fun warn(marker: Marker, msg: String)
    fun warn(marker: Marker, format: String, arg: Any?)
    fun warn(marker: Marker, format: String, arg1: Any?, arg2: Any?)
    fun warn(marker: Marker, format: String, vararg arguments: Any?)
    fun warn(marker: Marker, msg: String, t: Throwable)

    fun error(msg: String)
    fun error(format: String, arg: Any?)
    fun error(format: String, arg1: Any?, arg2: Any?)
    fun error(format: String, vararg arguments: Any?)
    fun error(msg: String, t: Throwable)
    fun error(marker: Marker, msg: String)
    fun error(marker: Marker, format: String, arg: Any?)
    fun error(marker: Marker, format: String, arg1: Any?, arg2: Any?)
    fun error(marker: Marker, format: String, vararg arguments: Any?)
    fun error(marker: Marker, msg: String, t: Throwable)
}
